Symfony/src/My/HomePageBundle/Form/TechnologyType.php
<?php

namespace My\HomePageBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class TechnologyType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('description')
            ->add('sites')
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'My\HomePageBundle\Entity\Technology'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'my_homepagebundle_technology';
    }
}

Symfony/src/My/HomePageBundle/Controller/PortfolioController.php
<?php

namespace My\HomePageBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use My\HomePageBundle\Entity\Site;

class PortfolioController extends Controller
{
    public function indexAction() {
        
        $sites = $this->getDoctrine()
                ->getRepository('MyHomePageBundle:Site')
                ->findAll();
        
        
        return $this->render('MyHomePageBundle:Portfolio:index.html.twig', array('sites' => $sites));
    }
}

Symfony/src/My/HomePageBundle/Resources/views/Portfolio/index.html.twig
{% extends 'MyHomePageBundle::base.html.twig' %}

{% block title %}Portfolio{% endblock %}

{% block navbar %}
    <ul>
        <li class="navItem"><a href="/symfony/web/app_dev.php">Home</a></li>
        <li class="navItem"><a href="/symfony/web/app_dev.php/cv">CV</a></li>
        <li class="navItemSelected"><a href="/symfony/web/app_dev.php/portfolio">Portfolio</a></li>
        <li class="navItem"><a href="/symfony/web/app_dev.php/contact">Contact</a></li>
    </ul>
{% endblock %}

{% block content %}
    <div class="portBox">
        {% for site in sites %}
            <section>
                <h3>{{ site.name }}</h3>
                <div><a href="{{ site.link }}" target='_blank'><img class="portScreen" src="../bundles/homepage/images/{{ site.path }}"></a></div>
                {% for technology in site.technologies %}
                    <img class="portTech" title="{{ technology.description }}" src="../bundles/homepage/images/{{ technology.description }}.png" />
                {% endfor %}
                <p>{{ site.description }}</p>
            </section>
        {% endfor %}
    </div>
{% endblock %}